// Auto-generated by tools/import-rushhour.js — do NOT edit by hand.
// Imported Rush Hour boards converted to Stray Arrows format.
// Chunk covers levels 1001..1200; not every level is present
// (gaps fall through to BAKED_LEVELS / procedural in generateLevel).
(function(){
  const chunk = {
  1001: {"cols":6,"rows":6,"arrows":[{"c":[[0,3],[0,2]],"d":2},{"c":[[0,4],[1,4]],"d":3},{"c":[[1,0],[1,1],[1,2]],"d":0},{"c":[[1,3],[2,3]],"d":3},{"c":[[2,0],[2,1]],"d":0},{"c":[[2,2],[3,2]],"d":3},{"c":[[2,5],[3,5]],"d":3},{"c":[[3,3],[3,4]],"d":0},{"c":[[5,0],[4,0]],"d":1},{"c":[[4,1],[4,2]],"d":0},{"c":[[4,3],[5,3]],"d":3},{"c":[[5,1],[5,2]],"d":0},{"c":[[5,4],[5,5]],"d":0}]},
  1034: {"cols":6,"rows":6,"arrows":[{"c":[[0,0],[0,1]],"d":0},{"c":[[0,3],[1,3]],"d":3},{"c":[[0,4],[1,4]],"d":3},{"c":[[1,0],[1,1],[1,2]],"d":0},{"c":[[2,0],[3,0]],"d":3},{"c":[[2,1],[2,2]],"d":0},{"c":[[2,3],[3,3]],"d":3},{"c":[[3,2],[4,2]],"d":3},{"c":[[3,4],[3,5]],"d":0},{"c":[[4,3],[4,4]],"d":0},{"c":[[4,5],[5,5]],"d":3},{"c":[[5,1],[5,2]],"d":0}]},
  1067: {"cols":6,"rows":6,"arrows":[{"c":[[0,0],[1,0]],"d":3},{"c":[[0,1],[0,2]],"d":0},{"c":[[1,3],[2,3]],"d":3},{"c":[[1,4],[1,5]],"d":0},{"c":[[2,0],[3,0]],"d":3},{"c":[[2,1],[2,2]],"d":0},{"c":[[3,2],[4,2]],"d":3},{"c":[[3,3],[3,4]],"d":0},{"c":[[5,5],[4,5],[3,5]],"d":1},{"c":[[4,0],[4,1]],"d":0},{"c":[[5,0],[5,1]],"d":0},{"c":[[5,2],[5,3],[5,4]],"d":0}]}
  };
  if (typeof window !== 'undefined') {
    window.IMPORTED_LEVELS = window.IMPORTED_LEVELS || {};
    Object.assign(window.IMPORTED_LEVELS, chunk);
    window.IMPORTED_LEVELS_CHUNK_5 = true;
  }
  if (typeof module !== 'undefined' && module.exports) module.exports = chunk;
})();
